version: '3.8'

services:
  node-app:
    build: .
    working_dir: /test-sse
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: test-sse
      MYSQL_USER: admin
      MYSQL_PASSWORD: 102030
      MYSQL_HOST: mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_DATABASE: test-sse
      MYSQL_USER: admin
      MYSQL_PASSWORD: 102030
    healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
        timeout: 20s
        retries: 10      
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data: